import "@/assets/styles/tailwind.css";

import { Overpass } from "next/font/google";

export const metadata: Metadata = {
  title: "Arda Eker - Interactive Rating Component",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.png",
  },
};

const font = Overpass({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({ children }: Layout) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
